### ISSUE TITLE
npm start，等一分钟后，cmd报错：Error: getaddrinfo ENOTFOUND localhost

### ISSUE THREAD

**Issue by YeWills** [ruizer/tsplayer#1]
如题，npm start 能编译成功， 但无法访问页面，npm start编译成功后，等一分钟，cmd报错：Error: getaddrinfo ENOTFOUND localhost

**Comment by YeWills** [comment]
解决方法 ： 打开host文件，增加一行：127.0.0.1 localhost
参考https://medium.com/thepolarlab/node-js-error-getaddrinfo-enotfound-localhost-b7ee35e1bb60

**Comment by ruizer** [comment]
对的，本地localhost没有配置的问题；
有时间可以看下webpack文档https://www.webpackjs.com/configuration/dev-server/#devserver-host，webpack.config.dev.js文件也可以修改devServer相关；

PS：刚刚改了个bug~   this指向问题

**Comment by ruizer** [comment]
@YeWills
